# Generated by Django 3.2.8 on 2021-10-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=500)),
                ('date', models.CharField(default=None, max_length=16)),
                ('price', models.PositiveIntegerField(default=None)),
                ('address', models.CharField(default=None, max_length=200)),
                ('animal_friendly', models.BooleanField(default=True)),
            ],
        ),
    ]
