# Generated by Django 3.2.8 on 2021-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
