# Generated by Django 3.2.8 on 2021-10-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('going', models.BooleanField(default=True)),
                ('join', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join', to='events.event')),
            ],
        ),
    ]
